### ISSUE TITLE
#Story: SWB TRE Implementation

### ISSUE THREAD

**Issue by vyshu1094** [Missouri-BMI/service-workbench-on-aws#23]
- [x] Missouri-BMI/service-workbench-on-aws#24
- [ ] Missouri-BMI/NextGen_Cloud_Architecture_AWS#106
- [ ] Missouri-BMI/NextGen_Cloud_Architecture_AWS#105

**Comment by vyshu1094** [comment]
From: Song, Xing <[xsm7f@health.missouri.edu](mailto:xsm7f@health.missouri.edu)>
Date: Tuesday, May 17, 2022 at 2:37 PM
To: Paka, Vyshnavi <[vpknx@health.missouri.edu](mailto:vpknx@health.missouri.edu)>, Ferguson, Shaun <[fergusonsha@umkc.edu](mailto:fergusonsha@umkc.edu)>, Bruce, Aaron <[abruce@umkc.edu](mailto:abruce@umkc.edu)>, znath <[znath@amazon.com](mailto:znath@amazon.com)>, travberk <[travberk@amazon.com](mailto:travberk@amazon.com)>, Mandhadi, Vasanthi (Medical Research Office) <[mandhadiv@health.missouri.edu](mailto:mandhadiv@health.missouri.edu)>, Raman, Balaji <[drbalaji@amazon.com](mailto:drbalaji@amazon.com)>, Gupta, Ananya <[ananyags@amazon.com](mailto:ananyags@amazon.com)>
Cc: Anye, Ernest <[anyeet@health.missouri.edu](mailto:anyeet@health.missouri.edu)>
Subject: RE: Initial test on upgraded SWB workspaces based on AppStream2.0

Hi, AWS team,
 
Thank you very much for meeting with us today and providing those great tips and insights! Very nice to meet you, Balaji and Ananya!
 
I’m sharing some brief meeting notes highlighting our next steps regarding the TRE upgrade:
 

1. we will create two new resource accounts: Application-TRE-Dev, Application-TRE-Prod, where we will deploy the TRE environments for studies using data with higher sensitivity. [@Bruce, Aaron](mailto:abruce@umkc.edu), [@Ferguson, Shaun](mailto:fergusonsha@umkc.edu)

2. we will follow-up with AWS SWB team with tips on configurations to improve the current performance of TRE - [@Bruce, Aaron](mailto:abruce@umkc.edu), please follow up with [@Raman, Balaji](mailto:drbalaji@amazon.com)

3. we will need to do some development work on allowing restricted access to only some pre-defined website for self-service package installation (something called squid). - [@znath](mailto:znath@amazon.com), [@travberk](mailto:travberk@amazon.com) I think we may need some tips from you to jumpstart this work. [@Bruce, Aaron](mailto:abruce@umkc.edu) and [@Ferguson, Shaun](mailto:fergusonsha@umkc.edu), what do you think?
4. I think I can live with waiting for 2-minutes every time restarting a workspace. Travis suggested a hybrid model of a constant running instance during working hours and turn into on-demand during after hours, which we can explore but need to be aware of the cost implication (this is not priority at the moment). - [@travberk](mailto:travberk@amazon.com),
5. we may want to explore this hybrid idea you brought up, any documentation that can be shared with us so that we can study a little bit?
we will schedule a AWS SWB preview meeting to learn about the next generation of SWB - [@Paka, Vyshnavi](mailto:vpknx@health.missouri.edu), please work with [@Gupta, Ananya](mailto:ananyags@amazon.com) to schedule a preview meeting within this group
 
[@Mandhadi, Vasanthi (Medical Research Office)](mailto:mandhadiv@health.missouri.edu) or [@Paka, Vyshnavi](mailto:vpknx@health.missouri.edu), can you help create github tickets for bullet points 1, 2, and 3 under our local fork of: [https://github.com/Missouri-BMI/service-workbench-on-aws](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMissouri-BMI%2Fservice-workbench-on-aws&data=05%7C01%7Cvpknx%40health.missouri.edu%7C7c171df3ab7846dbabc408da383caf8d%7Ce3fefdbef7e9401ba51a355e01b05a89%7C0%7C0%7C637884130533683020%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ra5FiY2rjfYhOn4t05t5Xw0i0VvRVVCe0UI66bjDZCA%3D&reserved=0), so that we can properly track the work?
 
Song

**Comment by fergusonsha-umkc** [comment]
Would it be OK if we name these accounts something other than Secure?  I don't want anyone to see those names and make the incorrect assumption our other services are not "secure" (this SWB instance would just be _more_ secure.  Application-TRE-Dev and Application-TRE-Prod, maybe, or something related to the classification of data it is intended for?)

Also need to know what the production URL for this instance should be, in complement to aws.nextgenbmi.umsystem.edu

@sxinger @mosaa @vasanthi014 @aaronmbruce

**Comment by fergusonsha-umkc** [comment]
Reply from Balaji on recommendations for AppStream 2.0 performance tuning:

Here are some links that you can follow to check how to configure your AppStream environment. You might have to do some trial and error for your use case to adjust the configs to optimize the performance.

For bandwidth recommendations see here - [https://docs.aws.amazon.com/appstream2/latest/developerguide/bandwidth-recommendations-user-connections.html](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.aws.amazon.com%2Fappstream2%2Flatest%2Fdeveloperguide%2Fbandwidth-recommendations-user-connections.html&data=05%7C01%7Cfergusonsha%40umkc.edu%7Cfe1ed05af2604bc001ea08da38dc4720%7Ce3fefdbef7e9401ba51a355e01b05a89%7C0%7C0%7C637884816014829860%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=j0iiXAsmtLF5D7RNuASLMegGymoNHU6ZbV1N6NaKYCM%3D&reserved=0)

For best practices see this - [https://docs.aws.amazon.com/whitepapers/latest/best-practices-for-deploying-amazon-appstream-2/best-practices-for-deploying-amazon-appstream-2.html](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.aws.amazon.com%2Fwhitepapers%2Flatest%2Fbest-practices-for-deploying-amazon-appstream-2%2Fbest-practices-for-deploying-amazon-appstream-2.html&data=05%7C01%7Cfergusonsha%40umkc.edu%7Cfe1ed05af2604bc001ea08da38dc4720%7Ce3fefdbef7e9401ba51a355e01b05a89%7C0%7C0%7C637884816014829860%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=P2VRj4ZQcwBgWN7Uo8bnQ6OB%2FrPs%2Fx3cSnqJup437ds%3D&reserved=0)

**Comment by mosaa** [comment]
@fergusonsha-umkc: Agreed.

**Comment by sxinger** [comment]
@fergusonsha-umkc Application-TRE-Dev and Application-TRE-Prod sounds good to me

**Comment by sxinger** [comment]
> Also need to know what the production URL for this instance should be, in complement to aws.nextgenbmi.umsystem.edu

how about: aws-tre.nextgenbmi.umsystem.edu

**Comment by fergusonsha-umkc** [comment]
I'll set things up accordingly :)

**Comment by fergusonsha-umkc** [comment]
Account email aliases requested, enrollment under Preparation OU to follow

**Comment by fergusonsha-umkc** [comment]
The two new TRE resource accounts will be fully Control Tower enrolled and ready to begin work in, after today.

**Comment by fergusonsha-umkc** [comment]
Application-TRE-Dev and Application-TRE-Prod are now fully enrolled under our organization Control Tower, next steps are to get them opted into the AppStream 2.0 beta in us-east-2 through Travis.  We can get that ball rolling now, or wait to see if its necessary once we're ready to begin working on building this 2nd SWB environment out, in the next month or two.

**Comment by fergusonsha-umkc** [comment]
It looks like AppStream 2.0 is available in us-east-2 (Ohio) region now, so these 2 accounts are all prepared to do a TRE install of Service Workbench, to live at aws-tre(-dev).nextgenbmi.umsystem.edu.  I'll attempt this in Application-TRE-Dev after we sort out the fundamental installation/upgrade brick-wall issue preventing further progress, which I aim to meet with Nathan to review this week, and in our Monday working session.

**Comment by fergusonsha-umkc** [comment]
On the topic of improving performance, under the existing Sandbox-TRE environment, @sxinger @vasanthi014 let me know your time constraints to coordinate incremental testing of adjusting the AppStream fleet instance resources to reach a happy point and check cost.  @aaronmbruce lets set up a time in the next couple weeks to review how this all plays together, to equalize knowledge.

**Comment by vasanthi014** [comment]
@Yaswitha-MU @soliman455 and I can test the new sandbox-TRE environment. We can work on it in sprint 17(Aug 14 - Aug 27)

**Comment by fergusonsha-umkc** [comment]
I'll get this environment updated to SWB v5.2.0 as well prior to further testing and tuning of performance.

**Comment by fergusonsha-umkc** [comment]
Posed a question to Travis, about TRE/AppStream and External Accounts in SWB:

"While updating our TRE Sandbox account to v5.2.0, and reviewing AppStream options, it occurred to me that an AppStream fleet might be needed under every account that TRE workspaces would be launched in, for example any separate external accounts in our organization which we've onboarded (we have one, Research-GPC).

Is this the case, or does the AppStream fleet running under the SWB main account get cross-account access to the workspace instances running on that other account's private subnets somehow?"

**Comment by fergusonsha-umkc** [comment]
Sigh.  After upgrading Sandbox-TRE from 4.3.1 to 5.2.0 both SSO and Cognito Native authentications are broken, even for the root user.  So I am debugging THAT now, using how Sandbox-Main's fresh Cognito configuration got deployed.  Added to the list of things that will go bonk during an upgrade of our Dev and Prod instances....

**Comment by fergusonsha-umkc** [comment]
Making progress.  I removed the broken Application entries from the SSO portal and will re-register them for both of the Sandbox SWB instances as soon as they are reconfigured properly and verified working with AWS SSO.

**Comment by fergusonsha-umkc** [comment]
The new URL for the Sandbox-TRE SWB instance is https://sandbox-tre.nextgenbmi.umsystem.edu and is working with AWS SSO again (yay)!  I'll get access groups reassigned tomorrow morning, for testing the latest version of TRE, next week

**Comment by fergusonsha-umkc** [comment]
Still in a holding pattern until I get time to focus on it

**Comment by fergusonsha-umkc** [comment]
As soon as we finalize the config of the 5.2.2 upgrade environment in Sandbox-Main and get through the Dev and Prod upgrade process to a stable point, this October, I'll mirror those environments in the TRE accounts and we can work on performance assessment and tuning of AppStream, and other implementations pertaining to this more restricted environment.

**Comment by fergusonsha-umkc** [comment]
Sandbox-TRE will be backed up to redeploy as desired, and repurposed as Sandbox-DevOps for more immediate needs
